#!/usr/bin/env python3
"""
Generate a REALISTIC SAP SmartEdit export — modeled as a genuine e-commerce
storefront (Nimbus Electronics), the same domain as this project's own
"real-spartacus-excerpt.impex" (SAP Commerce Cloud's Spartacus sample data).
Every row is meant to look like it could plausibly appear in a real customer's
export: real page/product copy, real distinct binary assets (see images/,
generated once by gen_assets.py — 7 images across 2 formats + a real PDF), and
references that are all genuinely resolvable — because that IS what most of a
real customer's data looks like.

The handful of imperfections below are the kind a real content team's data
ACTUALLY has, arrived at naturally rather than labeled as test cases:
  - a translation still in progress (Black Friday's French title isn't done yet)
  - two legal pages nobody has translated at all (Terms, Privacy)
  - a banner image a content editor removed without updating the component
    that still points at it (investor relations)
  - one long-form guide with real, substantial body copy
  - marketing copy with real punctuation (en dash, %, apostrophe)
  - a shared logo asset used in two different places (header + footer)
  - a deliberately thin/minimal page (404)

Nothing here is prefixed "edge" or "test" — the point is a report run against
this file should read like a real migration health check, not a fixture.
"""
import os

SCRIPT_DIR = os.path.dirname(__file__)
OUT_PATH = os.path.join(SCRIPT_DIR, "realistic-customer.impex")

LOCALES = ["en", "de", "fr"]


def q(s):
    if s is None or s == "":
        return ""
    t = str(s).replace("\r", " ").replace("\n", " ").replace('"', '""')
    return f'"{t}"'


lines = []


def header():
    lines.append("# =============================================================================")
    lines.append("# Nimbus Electronics — realistic SAP SmartEdit export for end-to-end validation.")
    lines.append("# Not a stress test: every reference/asset here is meant to resolve correctly,")
    lines.append("# the way most of a real customer's catalog does. The handful of imperfections")
    lines.append("# (a page mid-translation, an orphaned banner reference, two untranslated legal")
    lines.append("# pages) are the kind real content teams actually leave behind, not labeled test")
    lines.append("# rows. Backing images live in images/ (generated by gen_assets.py).")
    lines.append("# =============================================================================")
    lines.append("")
    lines.append("$catalogId = nimbusContentCatalog")
    lines.append("$contentCV = catalogVersion(CatalogVersion.catalog(Catalog.id[default=$catalogId]),CatalogVersion.version[default=Online])[default=$catalogId:Online]")
    lines.append("")


def block(type_name, header_cols, rows):
    lines.append(f"INSERT_UPDATE {type_name}; {header_cols}")
    for r in rows:
        lines.append(f"                          ; {r}")
    lines.append("")


header()

# ---- PageTemplate -----------------------------------------------------------
block(
    "PageTemplate",
    "uid[unique=true]; name; active",
    [
        f'homepageTemplate; {q("Homepage Template")}; true',
        f'categoryPageTemplate; {q("Category Page Template")}; true',
        f'contentPageTemplate; {q("Content Page Template")}; true',
        f'campaignPageTemplate; {q("Campaign Page Template")}; true',
    ],
)

# ---- Media (8 real distinct binaries + 1 dangling reference elsewhere) ------
MEDIA = [
    ("nimbusLogo", "image/png", "nimbus-logo.png"),
    ("homepageHeroBanner", "image/jpeg", "homepage-hero-banner.jpg"),
    ("camerasCategoryBanner", "image/png", "cameras-category-banner.png"),
    ("laptopsCategoryBanner", "image/png", "laptops-category-banner.png"),
    ("accessoriesCategoryBanner", "image/png", "accessories-category-banner.png"),
    ("summerSalePromo", "image/jpeg", "summer-sale-promo.jpg"),
    ("teamPhoto", "image/jpeg", "team-photo.jpg"),
    ("cameraBuyingGuideCover", "image/png", "camera-buying-guide-cover.png"),
    ("nimbusX200Datasheet", "application/pdf", "nimbus-x200-camera-datasheet.pdf"),
]
block(
    "Media",
    "code[unique=true]; mime; realfilename",
    [f"{code}; {mime}; {fname}" for code, mime, fname in MEDIA],
)

# ---- ContentPage --------------------------------------------------------------
# (uid, en, de, fr, template, label)
CAMERA_GUIDE_BODY_EXCERPT = (
    "Choosing your first mirrorless camera can feel overwhelming, so we broke "
    "it down into the four things that actually matter: sensor size, lens "
    "ecosystem, autofocus performance, and battery life. A larger sensor "
    "gathers more light, which means better low-light shots and shallower "
    "depth of field for portraits, but it also means larger, heavier lenses. "
    "If you shoot mostly outdoors in good light, an APS-C body like the "
    "Nimbus X200 gives you excellent image quality in a body that fits in a "
    "jacket pocket. If you shoot weddings or events indoors, a full-frame "
    "body will pay for itself in fewer blurry shots at f/1.8 and above."
)

PAGES = [
    ("homePage", "Nimbus Electronics — Home", "Nimbus Electronics — Startseite", "Nimbus Électronique — Accueil", "homepageTemplate", "home"),
    ("camerasCategory", "Cameras", "Kameras", "Appareils photo", "categoryPageTemplate", "cameras"),
    ("digitalCamerasSubcategory", "Digital Cameras", "Digitalkameras", "Appareils photo numériques", "categoryPageTemplate", "cameras/digital"),
    ("laptopsCategory", "Laptops", "Laptops", "Ordinateurs portables", "categoryPageTemplate", "laptops"),
    ("gamingLaptopsSubcategory", "Gaming Laptops", "Gaming-Laptops", "Portables de jeu", "categoryPageTemplate", "laptops/gaming"),
    ("accessoriesCategory", "Accessories", "Zubehör", "Accessoires", "categoryPageTemplate", "accessories"),
    ("aboutUsPage", "About Nimbus Electronics", "Über Nimbus Electronics", "À propos de Nimbus Électronique", "contentPageTemplate", "about-us"),
    ("contactUsPage", "Contact Us", "Kontaktieren Sie uns", "Contactez-nous", "contentPageTemplate", "contact-us"),
    ("careersPage", "Careers", "Karriere", None, "contentPageTemplate", "careers"),  # FR not translated yet
    ("pressPage", "Press & Media", "Presse & Medien", "Presse et médias", "contentPageTemplate", "press"),
    ("shippingInfoPage", "Shipping Information", "Versandinformationen", "Informations d'expédition", "contentPageTemplate", "shipping-info"),
    ("returnPolicyPage", "Return Policy", "Rückgaberecht", "Politique de retour", "contentPageTemplate", "return-policy"),
    ("helpFaqPage", "Help & FAQ", "Hilfe & FAQ", "Aide et FAQ", "contentPageTemplate", "help-faq"),
    ("termsOfServicePage", "Terms of Service", None, None, "contentPageTemplate", "terms-of-service"),  # legal, EN only
    ("privacyPolicyPage", "Privacy Policy", None, None, "contentPageTemplate", "privacy-policy"),  # legal, EN only
    ("summerSaleCampaign", "Summer Sale — Up to 40% Off!", "Sommerschlussverkauf — Bis zu 40% Rabatt!", "Soldes d'été — Jusqu'à 40% de réduction !", "campaignPageTemplate", "summer-sale"),
    ("blackFridayCampaign", "Black Friday Deals", "Black Friday Angebote", None, "campaignPageTemplate", "black-friday"),  # FR translation still in progress
    ("cameraBuyingGuide", "The Complete Camera Buying Guide", "Der komplette Kamera-Kaufratgeber", "Le guide complet d'achat d'appareil photo", "contentPageTemplate", "camera-buying-guide"),
    ("investorRelationsPage", "Investor Relations", "Investor Relations", "Relations avec les investisseurs", "contentPageTemplate", "investor-relations"),
    ("notFoundPage", "Page Not Found", None, None, "contentPageTemplate", "404"),
]

page_rows = []
for uid, en, de, fr, template, label in PAGES:
    de_cell = q(de) if de else ""
    fr_cell = q(fr) if fr else ""
    page_rows.append(f'{uid}; {q(en)}; {q(en)}; {de_cell}; {fr_cell}; {template}; {label}; false; approved')

block(
    "ContentPage",
    "uid[unique=true]; name; title[lang=en]; title[lang=de]; title[lang=fr]; masterTemplate(uid,$contentCV); label; defaultPage; approvalStatus(code)",
    page_rows,
)

# ---- CMSParagraphComponent ----------------------------------------------------
# (uid, name, en, de, fr) — fr=None means not translated
PARAGRAPHS = [
    ("homeIntroCopy", "Home Intro", "Everything you need for your next shoot, build, or setup — shipped in two days, backed by a two-year warranty.", "Alles, was Sie für Ihr nächstes Shooting, Ihren nächsten Build oder Ihr Setup brauchen — Lieferung in zwei Tagen, mit zweijähriger Garantie.", "Tout ce dont vous avez besoin pour votre prochaine séance photo, build ou installation — livré en deux jours, garanti deux ans."),
    ("camerasCategoryIntro", "Cameras Category Intro", "From your first mirrorless body to a full pro kit, our camera range covers every stage of the craft.", "Von Ihrer ersten spiegellosen Kamera bis zum vollständigen Profi-Kit — unser Kamerasortiment deckt jede Stufe ab.", "De votre premier appareil hybride à un kit professionnel complet, notre gamme couvre chaque étape."),
    ("laptopsCategoryIntro", "Laptops Category Intro", "Ultra-portable for travel, or maxed-out for rendering — our laptop lineup has a build for every workload.", "Ultra-portabel für unterwegs oder maximal ausgestattet fürs Rendering — für jede Arbeitslast das passende Modell.", "Ultra-portable pour voyager, ou surpuissant pour le rendu — un modèle pour chaque charge de travail."),
    ("accessoriesCategoryIntro", "Accessories Category Intro", "Cases, cables, tripods, and the small things that make the big things actually work.", "Taschen, Kabel, Stative und die kleinen Dinge, die die großen Dinge zum Laufen bringen.", None),
    ("aboutUsStory", "About Us Story", "Nimbus Electronics started in a garage in 2011 with a single question: why is buying a camera so confusing? Fifteen years later, we still answer every product question with a real person, not a chatbot script.", "Nimbus Electronics begann 2011 in einer Garage mit einer einzigen Frage: Warum ist der Kamerakauf so verwirrend? Fünfzehn Jahre später beantwortet bei uns immer noch ein echter Mensch jede Produktfrage.", "Nimbus Electronics a débuté dans un garage en 2011 avec une seule question : pourquoi acheter un appareil photo est-il si déroutant ? Quinze ans plus tard, une vraie personne répond encore à chaque question produit."),
    ("contactUsInstructions", "Contact Us Instructions", "Support is open Monday–Saturday, 8am–8pm. Most emails get a real reply within four hours.", "Der Support ist Montag bis Samstag von 8 bis 20 Uhr erreichbar. Die meisten E-Mails werden innerhalb von vier Stunden beantwortet.", "Le support est ouvert du lundi au samedi, de 8h à 20h. La plupart des e-mails reçoivent une réponse en quatre heures."),
    ("careersIntro", "Careers Intro", "We're a 40-person team that ships fast and argues about lens compression at lunch. Open roles below.", "Wir sind ein 40-köpfiges Team, das schnell liefert und beim Mittagessen über Objektivkompression diskutiert. Offene Stellen unten.", None),
    ("pressIntro", "Press Intro", "For interview requests or product loaner units, reach our press desk at press@nimbuselectronics.example.", "Für Interviewanfragen oder Testgeräte erreichen Sie unser Presseteam unter press@nimbuselectronics.example.", "Pour les demandes d'interview ou de prêt de matériel, contactez notre service de presse à press@nimbuselectronics.example."),
    ("shippingInfoCopy", "Shipping Info Copy", "Standard shipping is free over $75 and arrives in 2-4 business days. Express arrives next-day for orders placed before 2pm.", "Der Standardversand ist ab 75 $ kostenlos und dauert 2-4 Werktage. Der Expressversand erfolgt am nächsten Tag bei Bestellungen vor 14 Uhr.", "La livraison standard est gratuite dès 75 $ et arrive en 2 à 4 jours ouvrés. La livraison express arrive le lendemain pour les commandes passées avant 14h."),
    ("returnPolicyCopy", "Return Policy Copy", "Unopened items can be returned within 30 days for a full refund. Opened electronics can be exchanged within 14 days.", "Ungeöffnete Artikel können innerhalb von 30 Tagen zurückgegeben werden. Geöffnete Elektronik kann innerhalb von 14 Tagen umgetauscht werden.", "Les articles non ouverts peuvent être retournés sous 30 jours pour un remboursement complet. Les articles électroniques ouverts peuvent être échangés sous 14 jours."),
    ("helpFaqIntro", "Help FAQ Intro", "Can't find your answer here? Our support team is one click away, every day of the week.", "Ihre Antwort nicht gefunden? Unser Support-Team ist jeden Tag der Woche nur einen Klick entfernt.", "Vous ne trouvez pas votre réponse ? Notre équipe de support est à un clic, tous les jours de la semaine."),
    ("termsOfServiceBody", "Terms of Service Body", "By using this site you agree to our terms of sale, warranty terms, and acceptable use policy, each linked below.", None, None),
    ("privacyPolicyBody", "Privacy Policy Body", "We collect only what's needed to fulfill your order and never sell your data to third parties.", None, None),
    ("summerSaleCopy", "Summer Sale Copy", "Forty percent off select cameras and laptops, this week only. No code needed — the discount applies at checkout.", "Vierzig Prozent Rabatt auf ausgewählte Kameras und Laptops, nur diese Woche. Kein Code nötig — der Rabatt wird an der Kasse angewendet.", "Quarante pour cent de réduction sur une sélection d'appareils photo et d'ordinateurs portables, cette semaine seulement. Aucun code requis — la réduction s'applique à la caisse."),
    ("blackFridayCopy", "Black Friday Copy", "Our biggest discounts of the year land at midnight. Set a reminder — last year's top laptop deal sold out in nine minutes.", "Unsere größten Rabatte des Jahres gibt es um Mitternacht. Stellen Sie sich eine Erinnerung — das Top-Laptop-Angebot war letztes Jahr in neun Minuten ausverkauft.", None),
]

paragraph_rows = []
for uid, name, en, de, fr in PARAGRAPHS:
    de_cell = q(f"<p>{de}</p>") if de else ""
    fr_cell = q(f"<p>{fr}</p>") if fr else ""
    paragraph_rows.append(f'{uid}; {uid}; {q(name)}; {q(f"<p>{en}</p>")}; {de_cell}; {fr_cell}')

# The long-form buying guide gets its own row with genuinely long body copy.
guide_en = "<h2>Choosing Your First Mirrorless Camera</h2><p>" + CAMERA_GUIDE_BODY_EXCERPT + "</p>" * 4
guide_de = "<h2>Ihre erste spiegellose Kamera wählen</h2><p>Die Wahl Ihrer ersten spiegellosen Kamera kann überwältigend wirken, deshalb konzentrieren wir uns auf vier Dinge: Sensorgröße, Objektiv-Ökosystem, Autofokus-Leistung und Akkulaufzeit.</p>"
guide_fr = "<h2>Choisir votre premier appareil hybride</h2><p>Choisir votre premier appareil hybride peut sembler intimidant, alors concentrons-nous sur quatre éléments essentiels : la taille du capteur, l'écosystème d'objectifs, la performance de l'autofocus et l'autonomie de la batterie.</p>"
paragraph_rows.append(f'cameraBuyingGuideBody; cameraBuyingGuideBody; {q("Camera Buying Guide Body")}; {q(guide_en)}; {q(guide_de)}; {q(guide_fr)}')

block(
    "CMSParagraphComponent",
    "&componentRef; uid[unique=true]; name; content[lang=en]; content[lang=de]; content[lang=fr]",
    paragraph_rows,
)

# ---- CMSLinkComponent ---------------------------------------------------------
LINKS = [
    ("shopCamerasLink", "Shop Cameras", "/cameras"),
    ("shopLaptopsLink", "Shop Laptops", "/laptops"),
    ("shopAccessoriesLink", "Shop Accessories", "/accessories"),
    ("learnMoreCameraGuideLink", "Read the Buying Guide", "/camera-buying-guide"),
    ("contactSupportLink", "Contact Support", "/contact-us"),
    ("viewAllDealsLink", "View All Deals", "/summer-sale"),
    ("aboutUsLink", "About Us", "/about-us"),
    ("careersLink", "Careers", "/careers"),
    ("termsLink", "Terms of Service", "/terms-of-service"),
    ("privacyLink", "Privacy Policy", "/privacy-policy"),
]
block(
    "CMSLinkComponent",
    "&componentRef; uid[unique=true]; name; url; target(code)",
    [f'{uid}; {uid}; {q(name)}; {url}; sameWindow' for uid, name, url in LINKS],
)

# ---- CMSImageComponent (includes one genuinely dangling media reference) -----
IMAGES = [
    ("headerLogo", "Header Logo", "nimbusLogo"),
    ("footerLogo", "Footer Logo", "nimbusLogo"),  # same asset reused, legitimately
    ("homeHeroImage", "Home Hero Image", "homepageHeroBanner"),
    ("camerasCategoryImage", "Cameras Category Image", "camerasCategoryBanner"),
    ("laptopsCategoryImage", "Laptops Category Image", "laptopsCategoryBanner"),
    ("accessoriesCategoryImage", "Accessories Category Image", "accessoriesCategoryBanner"),
    ("summerSaleImage", "Summer Sale Image", "summerSalePromo"),
    ("teamPhotoImage", "Team Photo", "teamPhoto"),
    ("cameraGuideCoverImage", "Camera Guide Cover", "cameraBuyingGuideCover"),
    # This banner was retired from the DAM during a 2019 site refresh, but the
    # investor relations page's image component was never repointed at a
    # replacement — a real, if unglamorous, content-hygiene gap.
    ("investorRelationsBannerImage", "Investor Relations Banner", "investorRelationsBanner2019"),
]
block(
    "CMSImageComponent",
    "&componentRef; uid[unique=true]; name; media(code,$contentCV)",
    [f'{uid}; {uid}; {q(name)}; {media}' for uid, name, media in IMAGES],
)

# ---- CMSNavigationNode + CMSNavigationEntry -----------------------------------
NAV_NODES = [
    ("navHome", "Home", "Startseite", "Accueil"),
    ("navShop", "Shop", "Shop", "Boutique"),
    ("navSupport", "Support", "Support", "Assistance"),
    ("navCompany", "Company", "Unternehmen", "Entreprise"),
    ("navCameras", "Cameras", "Kameras", "Appareils photo"),
    ("navLaptops", "Laptops", "Laptops", "Ordinateurs portables"),
    ("navAccessories", "Accessories", "Zubehör", "Accessoires"),
]
block(
    "CMSNavigationNode",
    "&componentRef; uid[unique=true]; title[lang=en]; title[lang=de]; title[lang=fr]; visible",
    [f'{uid}; {uid}; {q(en)}; {q(de)}; {q(fr)}; true' for uid, en, de, fr in NAV_NODES],
)

NAV_ENTRIES = [
    ("navEntryShopToCameras", "navShop", "navCameras"),
    ("navEntryShopToLaptops", "navShop", "navLaptops"),
    ("navEntryShopToAccessories", "navShop", "navAccessories"),
    ("navEntryHomeToHomePage", "navHome", "homePage"),
    ("navEntrySupportToHelp", "navSupport", "helpFaqPage"),
    ("navEntrySupportToContact", "navSupport", "contactUsPage"),
    ("navEntrySupportToShipping", "navSupport", "shippingInfoPage"),
    ("navEntryCompanyToAbout", "navCompany", "aboutUsPage"),
    ("navEntryCompanyToCareers", "navCompany", "careersPage"),
    ("navEntryCompanyToPress", "navCompany", "pressPage"),
    ("navEntryCamerasToPage", "navCameras", "camerasCategory"),
    ("navEntryLaptopsToPage", "navLaptops", "laptopsCategory"),
    ("navEntryAccessoriesToPage", "navAccessories", "accessoriesCategory"),
    ("navEntryFooterTerms", "navSupport", "termsLink"),
    ("navEntryFooterPrivacy", "navSupport", "privacyLink"),
]
block(
    "CMSNavigationEntry",
    "uid[unique=true]; navigationNode(uid,$contentCV); item(&componentRef)",
    [f'{uid}; {node}; {target}' for uid, node, target in NAV_ENTRIES],
)

# ---- ContentSlot ---------------------------------------------------------------
# Shared header/footer slots, plus one hero + one body slot per page that needs one.
SLOT_ROWS = [
    ("globalHeaderSlot", "Global Header", "headerLogo,navEntryHomeToHomePage"),
    ("globalFooterSlot", "Global Footer", "footerLogo,navEntryFooterTerms,navEntryFooterPrivacy"),
]

HERO_SLOTS = {
    "homePage": "homeHeroImage",
    "camerasCategory": "camerasCategoryImage",
    "laptopsCategory": "laptopsCategoryImage",
    "accessoriesCategory": "accessoriesCategoryImage",
    "summerSaleCampaign": "summerSaleImage",
    "cameraBuyingGuide": "cameraGuideCoverImage",
    "aboutUsPage": "teamPhotoImage",
    "investorRelationsPage": "investorRelationsBannerImage",
}
for page_uid, image_uid in HERO_SLOTS.items():
    SLOT_ROWS.append((f"{page_uid}HeroSlot", f"{page_uid} Hero", image_uid))

BODY_SLOTS = {
    "homePage": ["homeIntroCopy", "shopCamerasLink", "shopLaptopsLink"],
    "camerasCategory": ["camerasCategoryIntro", "learnMoreCameraGuideLink"],
    "digitalCamerasSubcategory": ["camerasCategoryIntro"],
    "laptopsCategory": ["laptopsCategoryIntro"],
    "gamingLaptopsSubcategory": ["laptopsCategoryIntro"],
    "accessoriesCategory": ["accessoriesCategoryIntro"],
    "aboutUsPage": ["aboutUsStory", "aboutUsLink"],
    "contactUsPage": ["contactUsInstructions", "contactSupportLink"],
    "careersPage": ["careersIntro", "careersLink"],
    "pressPage": ["pressIntro"],
    "shippingInfoPage": ["shippingInfoCopy"],
    "returnPolicyPage": ["returnPolicyCopy"],
    "helpFaqPage": ["helpFaqIntro", "contactSupportLink"],
    "termsOfServicePage": ["termsOfServiceBody"],
    "privacyPolicyPage": ["privacyPolicyBody"],
    "summerSaleCampaign": ["summerSaleCopy", "viewAllDealsLink"],
    "blackFridayCampaign": ["blackFridayCopy", "viewAllDealsLink"],
    "cameraBuyingGuide": ["cameraBuyingGuideBody", "shopCamerasLink"],
    "investorRelationsPage": ["pressIntro"],
    "notFoundPage": [],  # deliberately thin — a real 404 page has almost nothing on it
}
for page_uid, members in BODY_SLOTS.items():
    if members:
        SLOT_ROWS.append((f"{page_uid}BodySlot", f"{page_uid} Body", ",".join(members)))

block(
    "ContentSlot",
    "uid[unique=true]; name; cmsComponents(uid,$contentCV)",
    [f'{uid}; {q(name)}; {members}' for uid, name, members in SLOT_ROWS],
)

# ---- ContentSlotForTemplate -----------------------------------------------------
TEMPLATES = ["homepageTemplate", "categoryPageTemplate", "contentPageTemplate", "campaignPageTemplate"]
sft_rows = []
for t in TEMPLATES:
    sft_rows.append(f"header-{t}; Header; {t}; globalHeaderSlot; true")
    sft_rows.append(f"footer-{t}; Footer; {t}; globalFooterSlot; true")
block(
    "ContentSlotForTemplate",
    "uid[unique=true]; position[unique=true]; pageTemplate(uid,$contentCV)[unique=true]; contentSlot(uid,$contentCV); allowOverwrite",
    sft_rows,
)

# ---- ContentSlotForPage -----------------------------------------------------------
sfp_rows = []
for page_uid, image_uid in HERO_SLOTS.items():
    sfp_rows.append(f"hero-{page_uid}; Hero; {page_uid}; {page_uid}HeroSlot")
for page_uid, members in BODY_SLOTS.items():
    if members:
        sfp_rows.append(f"body-{page_uid}; Body; {page_uid}; {page_uid}BodySlot")
block(
    "ContentSlotForPage",
    "uid[unique=true]; position[unique=true]; page(uid,$contentCV); contentSlot(uid,$contentCV)",
    sfp_rows,
)

with open(OUT_PATH, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

total_rows = sum(1 for l in lines if l.startswith("                          ;"))
print(f"Wrote {OUT_PATH}")
print(f"Approximate data rows: {total_rows}")
